title: Quite Frankly
email: frank@oppervoll-larsen.no
description: >
  Frank is occasionally writing about life, programming, gaming and other topics that
  spring to mind.
baseurl: ""
url: "https://crazyfraggle.github.io"
timezone: Europe/Oslo
whoami: >
  My name is Frank Oppervoll-Larsen, I'm a recently married father of two.  I
  work as a software developer in Microsoft, and write some software on my
  little spare time too. When bored, I'm usually playing Minecraft.
